config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :main_transactions do
    resources :transaction_items
  end
  resources :items do
    collection do
      get :select2
    end
  end
  resources :daily_reports, only: [:index, :show]
  resources :purchase_reports, only: [:index, :show]
  resources :sales_reports, only: [:index, :show]

  root 'items#index'

end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t('.app_title', default: 'Toko17'), root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to rails_admin_path do
            Admin
        %li{class: (params[:controller] == 'items' ? 'active' : '')}
          = link_to items_path do
            =t 'items.index.title'
        %li{class: (params[:controller] == 'main_transactions' ? 'active' : '')}
          = link_to main_transactions_path do
            =t 'main_transactions.index.title'
        %li{class: (params[:controller] == 'sales_reports' ? 'active' : '')}
          = link_to sales_reports_path do
            =t 'sales_reports.index.title'
        %li{class: (params[:controller] == 'purchase_reports' ? 'active' : '')}
          = link_to purchase_reports_path do
            =t 'purchase_reports.index.title'
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to t('.logout'), destroy_user_session_path, method: :delete