config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :main_transactions do
    resources :transaction_items
  end
  resources :items do
    collection do
      get :select2
    end
  end
  resources :daily_reports, only: [:index, :show]
  resources :purchase_reports, only: [:index, :show]
  resources :sales_reports, only: [:index, :show]

  root 'items#index'

end

app/controllers/main_transactions_controller.rb
class MainTransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_main_transaction, only: [:show, :edit, :update, :destroy]

  # GET /main_transactions
  # GET /main_transactions.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: MainTransactionDatatable.new(view_context) }
    end
  end

  # GET /main_transactions/1
  # GET /main_transactions/1.json
  def show
  end

  # GET /main_transactions/new
  def new
    @main_transaction = MainTransaction.new
  end

  # GET /main_transactions/1/edit
  def edit
  end

  # POST /main_transactions
  # POST /main_transactions.json
  def create
    @main_transaction = MainTransaction.new(main_transaction_params)

    respond_to do |format|
      if @main_transaction.save
        format.html { redirect_to @main_transaction, notice: 'Main transaction was successfully created.' }
        format.json { render :show, status: :created, location: @main_transaction }
      else
        format.html { render :new }
        format.json { render json: @main_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_transactions/1
  # PATCH/PUT /main_transactions/1.json
  def update
    respond_to do |format|
      if @main_transaction.update(main_transaction_params)
        format.html { redirect_to @main_transaction, notice: 'Main transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_transaction }
      else
        format.html { render :edit }
        format.json { render json: @main_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_transactions/1
  # DELETE /main_transactions/1.json
  def destroy
    @main_transaction.destroy
    respond_to do |format|
      format.html { redirect_to main_transactions_url, notice: 'Main transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_transaction
      @main_transaction = MainTransaction.includes(transaction_items: {item: {item_prices: :unit}}).references(transaction_items: {item: {item_prices: :unit}}).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_transaction_params
      params.require(:main_transaction).permit(:number, :transaction_date, :transaction_type_id, transaction_items_attributes: [:id, :_destroy, :item_id, :unit_id, :qty, :price])
    end
end

app/helpers/main_transactions_helper.rb
module MainTransactionsHelper
end

app/views/main_transactions/_form.html.haml
= simple_nested_form_for @main_transaction do |f|
  = f.error_notification

  .form-inputs
    = f.input :transaction_date, disabled: @main_transaction.persisted?, required: @main_transaction.new_record?
    = f.input :transaction_type_id, required: @main_transaction.new_record? do
      = f.collection_radio_buttons :transaction_type_id, TransactionType.all, :id, :name, item_wrapper_class: :radio do |b|
        = b.radio_button(data: { sign: b.object.sign }, class: 'main_transaction-transaction_type', checked: f.object.transaction_type_id == b.object.id, disabled: @main_transaction.persisted?) + b.text

    .panel.panel-default
      .panel-heading
        Barang
      %table.table
        %thead
          %tr
            %th.col-sm-4 Barang
            %th.col-sm-2 Unit
            %th.col-sm-1 Qty
            %th.col-sm-2 Harga
            %th.col-sm-2 Total
            %th.col-sm-1 Aksi
        %tbody#transaction_items
          = f.fields_for :transaction_items, wrapper: false
        %tfoot
          %tr
            %th{colspan: "2"} Total
            %th.main-transaction-total-qty
            %th.main-transaction-total-price
            %th.main-transaction-total-total-price
            %th
      .panel-body
        %p= f.link_to_add fa_icon('plus') + ' Barang', :transaction_items, :data => { :target => "#transaction_items" }

  .form-actions
    = f.button :submit

app/views/main_transactions/_transaction_item_fields.html.haml
%tr.fields
  %td
    .item-name
      - if f.object.persisted? || f.object.item_id.present?
        %p
          = f.object.item_title
        - if f.object.item.item_prices.length > 0
          %ul
            - f.object.item.ordered_item_prices.each do |item_price|
              %li= item_price.title
    - item_collections = []
    - if f.object.item_id.present?
      - item_collections = [[ f.object.item_title, f.object.item_id ]]
    = f.input :item_id, as: :select,            |
              collection: item_collections,     |
              include_blank: false,             |
              wrapper: :horizontal_form_nowrap, |
              input_html: { class: 'items-select2-ajax', data: { "ajax--url" => select2_items_path } }
  %td= f.association :unit, as: :radio_buttons, wrapper: :horizontal_radio_and_checkboxes_no_label, input_html: {class: 'transaction-item-unit'}
  %td= f.input :qty, wrapper: :horizontal_form_nowrap, input_html: {class: 'transaction-item-qty'}
  %td= f.input :price, wrapper: :horizontal_form_nowrap, input_html: {class: 'transaction-item-price'}
  %td= f.input_field :total_price, class: 'transaction-item-total-price form-control', disabled: true
  %td= f.link_to_remove fa_icon('trash-o')

app/views/main_transactions/edit.html.haml
= title t('.title')

%h1=t '.title'

= render 'form'

= link_to 'Show', @main_transaction
\|
= link_to 'Back', main_transactions_path

app/views/main_transactions/index.html.haml
= title t('.title')

%h1=t '.title'

= link_to fa_icon('plus') + ' Transaksi', new_main_transaction_path, class: 'btn btn-primary'

%br
%br

%table.table.table-hover.table-striped.table-bordered.table-condensed.datatable{width: '100%', id: "main-transactions-datatable", data: { processing: 'true', 'server-side' => 'true', ajax: main_transactions_path(format: :json), order: '[[0, "desc"]]' }}
  %thead
    %tr
      %th{data: { data: 'transaction_date' }} Tanggal Transaksi
      %th{data: { data: 'transaction_type_name' }} Tipe Transaksi
      %th{data: { data: 'total_price' }} Total
      %th{data: { data: 'action', orderable: 'false', searchable: 'false' }}
  %tbody

app/views/main_transactions/new.html.haml
= title t('.title')

%h1=t '.title'

= render 'form'

= link_to 'Back', main_transactions_path

app/views/main_transactions/show.html.haml
%p#notice= notice

%p
  %b Tanggal Transaksi:
  =l @main_transaction.transaction_date, format: :long
%p
  %b Tipe Transaksi:
  = @main_transaction.transaction_type_name
%p
  %b Total:
  = @main_transaction.total_price.to_f.to_s(:currency)

%table.table.table-hover.table-striped.table-bordered.table-condensed.datatable{data: { paging: 'false', order: '[]' }}
  %thead
    %tr
      %th Barang
      %th Unit
      %th.text-right Qty
      %th.text-right Harga
      %th.text-right Total
  %tbody
    - @main_transaction.transaction_items.each do |transaction_item|
      %tr
        %td= transaction_item.item_name
        %td= transaction_item.unit_title
        %td.text-right= transaction_item.qty.to_f.to_s(:rounded)
        %td.text-right= transaction_item.price.to_f.to_s(:currency)
        %td.text-right= transaction_item.total_price.to_f.to_s(:currency)
  %tfoot
    %tr
      %th{colspan: "2"} Total
      %th.text-right= @main_transaction.transaction_items.sum(:qty).to_f.to_s(:rounded)
      %th
      %th.text-right= @main_transaction.transaction_items.sum(:total_price).to_f.to_s(:currency)

= link_to 'Edit', edit_main_transaction_path(@main_transaction)
\|
= link_to 'Back', main_transactions_path