config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :main_transactions do
    resources :transaction_items
  end
  resources :items do
    collection do
      get :select2
    end
  end
  resources :daily_reports, only: [:index, :show]
  resources :purchase_reports, only: [:index, :show]
  resources :sales_reports, only: [:index, :show]

  root 'items#index'

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :uuid             not null, primary key
#  category_id :uuid
#  name        :string
#  abbr        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  autoid      :string
#  is_active   :boolean          default(TRUE)
#  barcode     :string
#
# Indexes
#
#  index_items_on_abbr         (abbr)
#  index_items_on_barcode      (barcode)
#  index_items_on_category_id  (category_id)
#  index_items_on_created_at   (created_at)
#  index_items_on_is_active    (is_active)
#  index_items_on_name         (name)
#
# Foreign Keys
#
#  fk_rails_89fb86dc8b  (category_id => categories.id)
#

class Item < ActiveRecord::Base
  # associations
  belongs_to :category, inverse_of: :items
  # has_many :item_stocks, inverse_of: :item, dependent: :restrict_with_error
  has_many :item_prices, -> { order("position asc") },
    inverse_of: :item, dependent: :restrict_with_error
  has_many :transaction_items, inverse_of: :item, dependent: :restrict_with_error
  has_many :daily_item_stocks, inverse_of: :item, dependent: :restrict_with_error

  accepts_nested_attributes_for :item_prices, allow_destroy: true

  # validations
  validates :name, presence: true
  validates :category, presence: true

  # delegate
  delegate :name, :title, to: :category, prefix: true, allow_nil: true

  def title
    name
  end

  def to_s
    title
  end

  def ordered_item_prices
    item_prices.sort_by do |item_price|
      item_price.position
    end
  end

  def self.select2(query)
    Item.includes(item_prices: :unit).where('("items"."name" ILIKE :query)', { query: "%#{sanitize_sql_like(query.downcase)}%" })
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:select2]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(view_context) }
    end
  end

  def select2
    @items = Item.select2(params[:q].to_s)
    respond_to do |format|
      format.json
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.includes(category: :parent, item_prices: :unit).references(category: :parent, item_prices: :unit).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category_id, :name, :is_active, item_prices_attributes: [:id, :_destroy, :unit_id, :position, :min_purchase, :max_purchase, :price, :is_base_price, :discount_percentage, :buy_price, :regular_sell_price])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= simple_nested_form_for @item do |f|
  = f.error_notification

  .form-inputs
    = f.association :category
    = f.input :name
    = f.input :is_active

    .panel.panel-default
      .panel-heading
        Harga
      %table.table
        %thead
          %tr
            %th Posisi
            %th Harga Jual
            %th Unit
            %th Harga Beli
            %th Min Pembelian
            %th Max Pembelian
            %th Aksi
        %tbody#item_prices
          = f.fields_for :item_prices, @item.ordered_item_prices, wrapper: false
      .panel-body
        %p= f.link_to_add fa_icon('plus') + ' Harga Baru', :item_prices, :data => { :target => "#item_prices" }

  .form-actions
    = f.button :submit

app/views/items/_item_price_fields.html.haml
%tr.fields
  %td= f.input :position, label: false, wrapper: false
  %td= f.input :price, label: false, wrapper: false
  %td= f.association :unit, as: :radio_buttons, wrapper: :horizontal_radio_and_checkboxes_no_label
  %td= f.input :buy_price, label: false, wrapper: false
  %td= f.input :min_purchase, label: false, wrapper: false
  %td= f.input :max_purchase, label: false, wrapper: false
  %td= f.link_to_remove fa_icon('trash-o')

app/views/items/edit.html.haml
= title t('.title')

%h1=t '.title'

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
= title t('.title')

%h1=t '.title'

= link_to fa_icon('plus') + ' Barang Baru', new_item_path, class: 'btn btn-primary'

%br
%br

%table.table.table-hover.table-striped.table-bordered.table-condensed.datatable{width: '100%', id: 'items-datatable', data: { processing: 'true', 'server-side' => 'true', ajax: items_path(format: :json) }}
  %thead
    %tr
      %th{data: { data: 'name' }} Nama
      %th{data: { data: 'category_title' }} Kategori
      %th{data: { data: 'item_prices' }} Harga Jual
      %th{data: { data: 'is_active', searchable: 'false' }} Aktif?
      %th{data: { data: 'action', orderable: 'false', searchable: 'false' }}
  %tbody

app/views/items/new.html.haml
= title t('.title')

%h1=t '.title'

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Kategori:
  = @item.category_title
%p
  %b Nama:
  = @item.name
%p
  %b Aktif?:
  = @item.is_active ? fa_icon('check') : fa_icon('times')

%table.table.table-hover.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th Posisi
      %th Harga Jual
      %th Unit
      %th Harga Beli
      %th Min Pembelian
      %th Max Pembelian
  %tbody
    - @item.ordered_item_prices.each do |item_price|
      %tr
        %td= item_price.position
        %td.text-right= item_price.price.to_f.to_s(:currency)
        %td= item_price.unit_title
        %td.text-right= item_price.buy_price.to_f.to_s(:currency)
        %td.text-right= item_price.min_purchase.to_f.to_s(:rounded)
        %td.text-right= item_price.max_purchase.to_f.to_s(:rounded)

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path